version: 0.2

env:
  variables:
    IMAGE_NAME: "simple-python-flash-app"
  parameter-store:
    DOCKER_USERNAME: /myflashapp/docker-cred/username
    DOCKER_PASSWORD: /myflashapp/docker-cred/password
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r day-14/simple-python-app/requirements.txt
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  build:
    commands:
      - cd day-14/simple-python-app/
      - echo "Building Docker Image"
      - docker build -t $IMAGE_NAME:latest .
      - docker tag $IMAGE_NAME:latest $DOCKER_USERNAME/$IMAGE_NAME:latest
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
  post_build:
    commands:
      - echo "Build is successful"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app
  name: dev-build-artifact
